### ISSUE TITLE
Mandatory naming for sketches

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/mon_school#103]
**Is your feature request related to a problem? Please describe.**
The new sketches mostly get saved as `A New Sketch` if no custom names are given before saving, which looks really unappealing. 

**Describe the solution you'd like**
Every sketch should be given a mandatory custom name before saving or it shouldn't be saved. 
No more `A New Sketch` on the sketches grid.

**Comment by pateljannat** [comment]
Resolved by #105
