### ISSUE TITLE
After (lines and polygon) chapter the web page is not available(staging.mon.school) website

### ISSUE THREAD

**Issue by ajju2003** [fossunited/mon_school#24]
**Describe the bug**
In (staging.mon.school ) website after lines and polygon chapter the web page is showing "there was an error building this page"
**To Reproduce**
1. Go to '..staging.mon.school.' website
2. Click on '...drawing shapes.' chapter
3. Scroll down to '...adding colours.'
5. showing error that there was a problem building  this page

**Expected behavior**
I expect to fix this problem 

**Screenshots**
![image](https://user-images.githubusercontent.com/87330000/125597219-d5f07717-96fa-40ba-805c-a93bbf310fea.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anandology** [comment]
Fixed now and the https://mon.school/ is now live with this version.
