### ISSUE TITLE
Page freezes when loading more sketches 

### ISSUE THREAD

**Issue by rijfas** [fossunited/mon_school#46]
**Describe the bug**
Site becomes unresponsive and browser lags heavily when loading sketches page.

**To Reproduce**
1. Go to https://mon.school/sketches
2. Scroll down to load more sketches 
3. Site becomes unresponsive and browser struggles (probably a memory leak while generating the thumbnails)

**Expected behavior**
Load remaining sketches thumbnails.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x86_64
 - Browser: Brave
 - Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) unknown (64-bit

**Additional context**
None

**Comment by rijfas** [comment]
sorry, already opened at #45 , my bad :cry:

**Comment by anandology** [comment]
Thanks @rijfas for reporting this issue. The page was freezing because it was taking too long time to render some of the complicated SVG images on the page. I've fixed this issue by replacing the images with PNG, making it lighter on the client.

**Comment by rijfas** [comment]
:+1:  Thanks man, btw nice interface and i really like the platform
