### ISSUE TITLE
Sketches: Text overflows outside the sketch card

### ISSUE THREAD

**Issue by nikochiko** [fossunited/mon_school#81]
**Describe the bug**
When the sketch is given a very long name, without spaces it overflows outside the card to other cards

**To Reproduce**
1. Go to https://mon.school/sketches -> submit a sketch
2. Give the sketch a very long name
3. Submit it
4. See the https://mon.school/sketches page for your entry

**Expected behavior**
The text should wrap or truncate to handle the overflow.

**Screenshots**
![image](https://user-images.githubusercontent.com/37668193/146176428-82a103d9-1b8b-43be-a272-09e52ca7f90d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macos
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by anandology** [comment]
Thanks for reporting this @nikochiko. Do you want to work on this?

**Comment by pateljannat** [comment]
This issue isn't there anymore. 

<img width="1327" alt="Screenshot 2022-07-26 at 9 16 28 AM" src="https://user-images.githubusercontent.com/31363128/180918695-a8f80739-3dc6-4d8f-8c82-065fcc616f60.png">
